openapi: 3.0.0
info:
  title: Health Tracking API
  description: Service for receiving batch health metrics from IoT devices and mobile apps.
  version: 1.0.0

paths:
  /meals:
    post:
      summary: Report a batch of meal events
      operationId: storage.process_meal_batch
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Meal'
      responses:
        '201':
          description: Batch successfully received
        '400':
          description: Invalid batch format
    get:
      summary: gets new meals marconutrients reading
      operationId: storage.get_meals_reading
      parameters:
        - name: start_timestamp
          in: query
          description: start of the timespan
          schema:
            type: string
            format: date-time
            example: 2016-08-29T09:12:33.001Z
        - name: end_timestamp
          in: query
          description: end of the timespan
          schema:
            type: string
            format: date-time
            example: 2016-08-29T09:12:33.001Z
      responses:
        '200':
          description: successfully returned a list of meal marconutrients
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Meal'
        '400':
          description: Invalid batch format
  /exercises:
    post:
      summary: Report a batch of exercise events
      operationId: storage.process_exercise_batch
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Exercise'
      responses:
        '201':
          description: Batch successfully received
        '400':
          description: Invalid batch format
    get:
      summary: gets new exercise reading
      operationId: storage.get_exercise_reading
      parameters:
        - name: start_timestamp
          in: query
          description: start of the timespan
          schema:
            type: string
            format: date-time
            example: 2016-08-29T09:12:33.001Z
        - name: end_timestamp
          in: query
          description: end of the timespan
          schema:
            type: string
            format: date-time
            example: 2016-08-29T09:12:33.001Z
      responses:
        '200':
          description: successfully returned a list of exercise
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Exercise'
        '400':
          description: Invalid batch format
components:
  schemas:
    Meal:
      type: object
      required: [meal_id, calories, meal_type]
      properties:
        trace_id: {type: string, format: uuid}
        user_id: { type: string, format: uuid }
        batch_timestamp: { type: string, format: date-time }
        source_device: { type: string, example: "iPhone 15 Pro", description: "The device that captured this data" }
        record_timestamp: { type: string, format: date-time }
        meal_id: { type: string, format: uuid }
        calories: { type: integer, minimum: 0 }
        meal_type: { type: string, enum: [Breakfast, Lunch, Dinner, Snack] }
        carbs_g: { type: integer, minimum: 0 }
        protein_g: { type: integer, minimum: 0 }
        fat_g: { type: integer, minimum: 0 }

    Exercise:
      type: object
      required: [exercise_id, type, duration_min, avg_heart_rate]
      properties:
        trace_id: {type: string, format: uuid }
        user_id: { type: string, format: uuid }
        batch_timestamp: { type: string, format: date-time }
        source_device: { type: string, example: "Garmin Forerunner 955", description: "The device that captured this data" }
        record_timestamp: { type: string, format: date-time }
        exercise_id: { type: string, format: uuid }
        type: { type: string, example: "Running" }
        duration_min: { type: integer, minimum: 1 }
        avg_heart_rate: { type: integer, minimum: 30 }
        peak_heart_rate: { type: integer, minimum: 30 }
